### ISSUE TITLE
Dezinfekčne tablety

### ISSUE THREAD

**Issue by kubob** [pexelnet/starving#2]
Tablety, ktoré po zlúčení s nepitnou vodou vyvolajú chemickú reakciu. Tá spôsobí 100% vyčistenie vody. Bude to v tom okamžiku (žiadne čakanie). Voda je maximálne čistá, bez akejkoľvek možnosti ochorenia.

Vyrobí sa to zlúčením 2 flaštičiek Chlóru (chlór = argón + síra) následne uvarených v peci (chlórový prášok) Následne sa iba zmieša s nečistou vodou a vznikne čistá (pitná) voda.
#7

**Comment by dobrakmato** [comment]
Som za.

**Comment by janscz** [comment]
Ano jsem pro, takto tyto tablety fungují i ve skutečnosti

**Comment by pitkes22** [comment]
Som za ich existencu ale som proti tomu aby sa dali len tak najsť , vzhľadom na to ze bola planovana nieaka chemia tak by som to zaradil ako jeden z produktou ktore sa budu pomocou nej dat vytvoriť .

**Comment by janscz** [comment]
Ty tablety by měli být k nalezení v místech kde bys to čekal jako třeba sklad chemičky, sklad vojenského materiálu a třeba i lékárna

**Comment by dobrakmato** [comment]
#7

**Comment by pitkes22** [comment]
áno ale chcem aby bolo jednoduchšie tie tablety vyrobiť ako kvôli nim prejsť pol sveta do "chemičky"...

**Comment by dobrakmato** [comment]
Preco by bolo treba prejst pol sveta?

**Comment by pitkes22** [comment]
lebo predpokladam že chemička nieje vec ktora je na každom rohu ...

**Comment by janscz** [comment]
Ano výborně chemička není na každém rohu pravda a co lékárna ? ty jako neexistujou ?.
Já bych to nechatl tak, že ty tablety půjde pouze najít

**Comment by dobrakmato** [comment]
Tak ich nechajme aj ako drop a nechajme aj spôsob výroby z chemikálií.

**Comment by pitkes22** [comment]
Ok, ale nechal by som ich aby boli vzacne ....

**Comment by dobrakmato** [comment]
@kubob Aktualizuj prvy post.

Dňa Sat Jan 31 2015 at 11:53:52 pitkes22 notifications@github.com
napísal(a):

**Comment by dobrakmato** [comment]
@kubob Z coho by mali byt zlozene dezinfekcne tablety ( vzhladom ku #7 )?

**Comment by kubob** [comment]
Chlór= Síra + Argón. Získanie týchto 2 kyselín som popísal #7

---

Bolo by možné aby sa upečením (v peci) z NIEČOHO? Síra by sa dala použíť na dezinfekčné tablety (síra+argon=chlor)

Argon by sa dal získať zo vzduchu.

**Comment by dobrakmato** [comment]
@kubob Potrebujeme mapping: 
https://github.com/pexelnet/starving/blob/master/ISSUE_ITEM.md 
http://starving.eu/mapping.php.

**Comment by dobrakmato** [comment]
Zrusene. Nebude implementovane.
