### ISSUE TITLE
Crafting - zdrojové materiály

### ISSUE THREAD

**Issue by dobrakmato** [pexelnet/starving#23]
V hre by sa budú veci vyrábať iba zo zdrojových materiálov ako napríklad oceľ (železo), sklo, látka...

**Comment by kubob** [comment]
Neviem ako inak by si to chcel spraviť. Takže súhlasím.

**Comment by janscz** [comment]
Souhlasím -> je nutné udělat soupis zdrojových věcí

**Comment by pitkes22** [comment]
@janscz O chvilu pribudne zoznam všetkych itemou

**Comment by dobrakmato** [comment]
@pitkes22 Mohol by si sa aspon vyjadrit k originalnemu postu, ked uz pod nim komentujes?

**Comment by pitkes22** [comment]
No nesuhlasim s nim ...lebo ak by sa vyrabali iba zo zdrojovich materialou tak napriklad roztrhanim trička si neurobiš bandaž ....

**Comment by dobrakmato** [comment]
@pitkes22 Nemas ziaden iny napad, teda ostava tento.

**Comment by pitkes22** [comment]
@dobrakmato No podla mna celi tento  issue  je uplne zbytocny ... veci sa proste budu craftit podla crafting receptu do ktoreho moze ist hocico na com sa dohodneme ...

**Comment by dobrakmato** [comment]
Tento issue zatvaram nakolko momentalne nema ziaden vyznam.
