### ISSUE TITLE
Choroby ľudí - všeobecne

### ISSUE THREAD

**Issue by kubob** [pexelnet/starving#3]
Nakazenie: vypitie nepitnej (špinavej) vody / zjedenie zhnitého (zkazené) jedlo / infekcia

Priebeh: 

Následky:
               - zhoršenie všetkých (alebo takmer všetkých) životných funkcií (rýchlejšie míňanie staminy etc)
             - spomalenie movementu (pohybu)

**Comment by janscz** [comment]
Není to tu jasné, je možné na to umřít ? Já bych byl pro aby se na nemoc dalo umřít při neléčení

**Comment by pitkes22** [comment]
Ale nie každa choroba je smrtelna ...

**Comment by janscz** [comment]
Ano na rýmu asi neumřeš, ale umřeš na cokoliv na co potřebuješ nějakou léčbu tzn. zabije tě jakákoliv infekce

**Comment by dobrakmato** [comment]
@kubob V nadpise je choroby, ale v texte je iba jedna choroba.

**Comment by kubob** [comment]
@dobrakmato Spravil som to všeobecne.
