### ISSUE TITLE
Socha v hlavnom meste.

### ISSUE THREAD

**Issue by pitkes22** [pexelnet/starving#52]
Na namesti v hlavnom meste sa bude nechadzať socha zo zlata inšpirovana tymto navrhom:
![GitHub Logo](http://i.imgur.com/wyxp1c4.jpg)
Na soche bude tabulka s textom: Pitkes je užasny !!!!

**Comment by kubob** [comment]
Pitkes je úžasný! (tie 4 vykríčniky s medzerou medzi koncom vety a nimi fakt nie)

**Comment by dobrakmato** [comment]
Asi nie.

**Comment by janscz** [comment]
Určitě jsem proti
