### ISSUE TITLE
Mapping zbrani s vylepseniami

### ISSUE THREAD

**Issue by pitkes22** [pexelnet/starving#61]
<h2>M16</h2>

**M16** : `IRON_INGOT:0`
**M16(mierenie ak na zbrani nieje ziaden scope)** : `WOOL:0`
**M16 + silencer** : `WOOL:1`
**M16 + foregrip** : `WOOL:2`
**M16 + scope** : `WOOL:3`
**M16 + silencer +  foregrip** : `WOOL:4`
**M16 + silencer + scope** : `WOOL:5`
**M16 + scope + foregrip** : `WOOL:6`
**M16 + silencer + scope + foregrip** : `WOOL:7`

<h2>Revolver</h2>

**Revolver** : `WOOL:8`
**Revolver(mierenie ak na zbrani nieje ziaden scope)** : `WOOL:9`
**Revolver + silencer** : `WOOL:10`
**Revolver + scope** : `WOOL:11`
**Revolver + silencer + scope** : `WOOL:12`

**Comment by dobrakmato** [comment]
@pitkes22 Preco toto nie je pri zbraniach alebo pri vylepseniach?
