### ISSUE TITLE
Zvetsovac koliznej plochy blockov s modelom vysokym viac ako 1 block

### ISSUE THREAD

**Issue by pitkes22** [pexelnet/starving#64]
Ak sa položi block špecifikovany niekde v configu položi sa nad neho block barrieri. 
Ak sa rozbije block barieri overi sa ci pod nou nebol block špecifikovany v konfigu a ak ano tak sa tiež rozbije.
Ak hrač klikne na block barrieri vykona sa akcia ako keby klikol na block pod nou.

**Comment by dobrakmato** [comment]
Chyba popis struktury configu + priklad.

Myslim, ze sa nebudu bariery ukladat len **nad** block.

Okrem toho je struktura issue zla a vety su zle stavane a stylizovane. Chybaju v nich bodky a ciarky.
